apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-backend
  template:
    metadata:
      labels:
        app: customer-management-backend
    spec:
      containers:
      - name: customer-management-backend
        image: srikanth8/customer-management-backend:latest
        env:
        - name: BACKEND_URL
          value: "http://customer-management-backend-service.default.svc.cluster.local:80"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-management-backend-service
spec:
  selector:
    app: customer-management-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer
